### ISSUE TITLE
Remove unused code and include attributions

### ISSUE THREAD

**Issue by thanasions** [datasciencecampus/patent_app_detect#34]
- [x] scripts/visualization/wordclouds/multicloudplot.py remove unused fn
- [x] scripts/algorithms/tfidf.py - attribute analyser and tokenisers
- [x] Cite outputs/fdg/knockout-3.4.2.js attribution in README.md
- [x] Add note to README.md about 3rd party library usage, see GitHub network page
- [x] output/fdg attribute to https://github.com/Aeternia-ua/WebGenresForceDirectedGraph

**Comment by IanGrimstead** [comment]
Created branch 34-attributions
