### ISSUE TITLE
json output config file

### ISSUE THREAD

**Issue by thanasions** [datasciencecampus/patent_app_detect#47]
Json needs to include:

absolute_path_pkl (of pickled file used as input),
absolute_path_tech_report (of tech_report.txt),
cpc
year_from,
year_to,
pick,
time<bool>,
cite<bool>,
focus<bool>

**Comment by IanGrimstead** [comment]
Created branch 47-json-config

**Comment by IanGrimstead** [comment]
Use case: `-json` will trigger output of a .json file alongside the report .txt file in `outputs\reports`
Report name is same for json (just different file extension)

**Comment by thanasions** [comment]
{
	"paths": {
		"data": "absolute_path",
		"tech_report": "absolute_path"
	},
	"year": {
		"from": "blah",
		"to": "blah"
	},
	"parameters": {
		"pick": "blah",
		"time": false,
		"cite": false,
		"focus": false
	}
}
