### ISSUE TITLE
lemmatizer probs

### ISSUE THREAD

**Issue by thanasions** [datasciencecampus/patent_app_detect#61]
**Describe the bug**
Lemmatizer often seems to be failing. For example, the tf-idf matrix contains:

_abrasion resistance_ and _abrasion resistant_
_heat_exchange_ and _heat_exchanger_

**To Reproduce**
Create a tf-idf matrix with USPTO-random-500000-term_present.pkl.bz2

**Expected behavior**
look for the above terms and try to find out why is this happening. Does it not unify if it sees a verb and a noun for example. Can we improve this?

**Comment by IanGrimstead** [comment]
That's a sweet fix! How'd you spot it?

**Comment by IanGrimstead** [comment]
PS I'd like a unit test on that one (happy to write it) so for my curiosity see before/after the code change... this change may be what blew the other unit tests...
