### ISSUE TITLE
improve n-gram count accuracy

### ISSUE THREAD

**Issue by thanasions** [datasciencecampus/patent_app_detect#66]
At the moment ngrams scoring is biased due to the fact that any ngram is contained in its (n+1)gram. Consider the example: big data analytics, big data and data analytics. The trigram gets the same count as the bigrams it contains. The bigrams also collect scoring from other documents they exist as a bi-gram term, hence a higher rank. This is why the ranks are always dominated with terms of lower n

We need to scan the tf-idf matrix row by row and nullify the tf-idf score for n-grams contained within a (n+1)gram. This way we will achieve better term distribution accross a given n-gram range.

**Comment by IanGrimstead** [comment]
Here's a thought - just eyeballed the code; if `term n` contains `term n+1`, it'll throw away `term n+1` (sounds good). What about `term q` - it could also be contained in `term n`. If they're alphabetical...
e.g. `liquid crystal display` will be next to `liquid crystal` (as terms are stored alphabetically). How about `crystal display`? [caveat - assuming I've read the code correctly]
