### ISSUE TITLE
Restore txt report

### ISSUE THREAD

**Issue by thanasions** [datasciencecampus/patent_app_detect#68]
The output report looks different and messy at the moment. Need to restore it to its previous state, as a single column sorted list.

**Comment by IanGrimstead** [comment]
Lack of line breaks by the looks of it...

**Comment by IanGrimstead** [comment]
Approx line 155 onwards needs to be:
```
        for score, term in dict_freqs.items():
            file.write(f' {term:30} {score:f}\n')
            print(f'{counter}. {term:30} {score:f}')
```
